version: '3.9'

services:
  mysql_db:
    container_name: mysql_db
    hostname: mysql_db
    image: mysql:latest
    restart: always
    command:
      - --authentication-policy=mysql_native_password 
    volumes: 
      - ./mysql_db:/var/lib/mysql 
    ports: 
      - 3306:3306  
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: mysql
      - MYSQL_USER: user
      - MYSQL_PASSWORD: password 
    TZ: America/SaoPaulo 